#!/bin/sh
# Build the pet binary and Pet.app into build/, install the app to
# ~/Applications, and restart the running pet.
set -e
cd "$(dirname "$0")"

BUILD="build"
APP="$BUILD/Pet.app"

mkdir -p "$BUILD"

# Compile the default skins into the binary, generated from Skins/ so those
# files remain the single source of truth.
python3 - > "$BUILD/DefaultSkins.swift" <<'GEN'
import pathlib
print("// Generated by build.sh from Skins/ — do not edit.")
print("enum DefaultSkinData {")
print("    static let files: [(name: String, json: String)] = [")
for f in sorted(pathlib.Path("Skins").glob("*.petskin")):
    text = f.read_text().rstrip("\n")
    assert '"""#' not in text, f"{f} contains the raw-string terminator"
    print(f'        ("{f.name}", #"""')
    print(text)
    print('"""#),')
print("    ]")
print("}")
GEN

# Universal binary with a real deployment target. Without -target, swiftc uses
# the building machine's OS as the minimum, so the app refuses to launch on
# anything older — and builds only for the host architecture.
DEPLOY_TARGET=12.0
for arch in arm64 x86_64; do
    swiftc -swift-version 5 -O \
        -target "$arch-apple-macos$DEPLOY_TARGET" \
        -o "$BUILD/pet-$arch" main.swift Sources/*.swift "$BUILD/DefaultSkins.swift"
done
lipo -create -output "$BUILD/pet" "$BUILD/pet-arm64" "$BUILD/pet-x86_64"
rm -f "$BUILD/pet-arm64" "$BUILD/pet-x86_64"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BUILD/pet" "$APP/Contents/MacOS/Pet"
cp -R Skins "$APP/Contents/Resources/Skins"

# App icon, drawn by the app itself from the same vector art as the pet.
ICONSET="$BUILD/Pet.iconset"
rm -rf "$ICONSET"; mkdir -p "$ICONSET"
"$BUILD/pet" --icon 1024 "$BUILD/icon.png"
for spec in "16 icon_16x16" "32 icon_16x16@2x" "32 icon_32x32" "64 icon_32x32@2x" \
            "128 icon_128x128" "256 icon_128x128@2x" "256 icon_256x256" \
            "512 icon_256x256@2x" "512 icon_512x512" "1024 icon_512x512@2x"; do
    set -- $spec
    sips -z "$1" "$1" "$BUILD/icon.png" --out "$ICONSET/$2.png" >/dev/null 2>&1
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/Pet.icns"
cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>Pet</string>
    <key>CFBundleDisplayName</key><string>Desktop Pet</string>
    <key>CFBundleIdentifier</key><string>local.desktop.pet</string>
    <key>CFBundleExecutable</key><string>Pet</string>
    <key>CFBundleIconFile</key><string>Pet</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>LSUIElement</key><true/>
    <key>LSMinimumSystemVersion</key><string>12.0</string>
</dict>
</plist>
PLIST
codesign --force --deep -s - "$APP" >/dev/null 2>&1

if [ "$1" = "--no-install" ]; then
    echo "built:     $(pwd)/$APP"
    echo "           $(pwd)/$BUILD/pet"
    exit 0
fi

pkill -f "Pet.app/Contents/MacOS/Pet" 2>/dev/null || true
sleep 1
mkdir -p "$HOME/Applications"
rm -rf "$HOME/Applications/Pet.app"
cp -R "$APP" "$HOME/Applications/Pet.app"
open "$HOME/Applications/Pet.app"

echo "built:     $(pwd)/$APP"
echo "           $(pwd)/$BUILD/pet"
echo "installed: ~/Applications/Pet.app (running)"
